---
## created by grolston@outlook.com

## The following CloudFormation deploys a simple Linux EC2 
## that leverages Docker in Docker to execute Gitlab Runner.
## The installation of runner is on a privileged level to 
## allow Docker to create more Docker containers. Due to this
## the EC2 will need to be isolated.

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation installation of Gitlab Runner on Linux EC2 with Docker in Docker executor
Parameters:
  KeyPair: 
    Description: key pair
    Type: AWS::EC2::KeyPair::KeyName
  RunnerURL:
    Description: Specify the following URL during the Runner setup
    Type: String
    Default: 'https://gitlab.com/'
  RunnerToken:
    Description: Use the following registration token during setup
    Type: String
  RunnerName:
    Description: Friendly name of the runner agent to be seen on gitlab web UI
    Type: String
  Role:
    Type: String
    Description: Enter the role name (instance profile) to apply to the ec2 instance.
  Subnet:
    Description: The subnet to launch the instance in to.
    Type: AWS::EC2::Subnet::Id
  SecurityGroup:
    Description: List of AWS Security Groups. Select one or many.
    Type: List<AWS::EC2::SecurityGroup::Id>
  OperatingSystem:
    Description: Operating System Desired
    Type: String
    Default: AWSLinux
    AllowedValues:
    - AWSLinux
    - CentOS.6.7
    - CentOS.7.3
  InstanceType:
    Description: Desired Instance Size. Recommended to se t2.micro for cost-savings
    Type: String
    Default: t2.micro
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - m3.large
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m4.16xlarge
    - m5.large
  TagKeyName:
    Description: 'Required: Enter the name of the key for the key-value. You''ll enter the actual value of the tag next.'
    Default: Name
    Type: String
    MinLength: 1
  TagValue:
    Description: 'Required: Enter the tag you''d like applied to the instance.'
    Type: String
    MinLength: 1
  VolumeSize:
    Description: Enter the number of GBs you want your volume to be. The minimum value
      is 8 GBs
    Type: Number
    Default: 8
    MinValue: 8
Mappings:
  OS:
    AWSLinux:
      amiID: ami-bf4193c7
      rootBlock: "/dev/sda1"
    CentOS.6.7:
      amiID: ami-05cf2265
      rootBlock: "/dev/sda1"
    CentOS.7.3:
      amiID: ami-8e2c9aee
      rootBlock: "/dev/sda1"
Conditions:
  HasKeyName: !Not [ !Equals ["", !Ref KeyName ] ]
  HasRole: !Not [ !Equals ["", !Ref KeyName ] ]
Resources:
  LinuxEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ OS, !Ref OperatingSystem, amiID ]
      InstanceType: !Ref InstanceType
      KeyName: !If [HasKeyName, !Ref KeyName, !Ref AWS::NoValue]
      Monitoring: 'true'
      IamInstanceProfile: !If [HasRole, !Ref Role, !Ref AWS::NoValue]
      SourceDestCheck: 'true'
      SubnetId: !Ref Subnet
      SecurityGroupIds: !Ref SecurityGroup
      BlockDeviceMappings:
      - DeviceName: !FindInMap [ OS, !Ref OperatingSystem, rootBlock ]
        Ebs:
          VolumeSize: !Ref VolumeSize
      Tags:
      - Key: !Ref TagKeyName
        Value: !Ref TagValue
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          setenforce permissive
          cd /root/
          yum install git -y
          # install docker - docker ce does not work on RedHat so CentOS or AWSLinux is needed
          curl -sSL https://get.docker.com/ | sh
          ## rpm for RHEL-based systems
          curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | sudo bash
          systemctl enable docker && systemctl start docker
          useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash
          usermod -aG docker gitlab-runner

          yum install gitlab-runner -y
          gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner
          gitlab-runner start

          gitlab-runner register \
            --url ${RunnerURL}  \
            --registration-token ${RunnerToken}  \
            --executor docker   \
            --description ${RunnerName}   \
            --docker-image "docker:latest"   \
            --docker-volumes /var/run/docker.sock:/var/run/docker.sock \
            --docker-privileged \
            --non-interactive

Outputs:
  MyInstanceId:
    Description: Resource ID of the newly created EC2 instance
    Value:
      Ref: LinuxEc2
